# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    container_name: stockdesk-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "postgres_data:/var/lib/postgresql"
    
volumes:
  postgres_data:
